name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        cfg:
        - conda-env: base_6
          python-version: 3.6
        - conda-env: test_env
          python-version: 3.7
        - conda-env: base_8
          python-version: 3.8

    env: 
      PYVER: ${{ matrix.cfg.python-version }}
      CONDA_ENV: ${{ matrix.cfg.conda-env }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup Information
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
        conda --version
    - name: Create Environment
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate
        python devtools/scripts/create_conda_env.py -n=test -p=$PYVER devtools/conda-envs/$CONDA_ENV.yaml
    - name: Install
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        python -m pip install . --no-deps
    - name: Environment Information
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        conda list --show-channel-urls
    - name: PyTest
      shell: bash
      run: |
        eval "$(conda shell.bash hook)" && conda activate test
        pytest -rws -v --cov=moly --color=yes --cov-report=xml moly/
    - name: CodeCov  
      uses: codecov/codecov-action@v1